name: Build docker images

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  multi-registries:
    runs-on: ubuntu-22.04

    steps:
      - name: Get current date
        id: current_date_time
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYYMMDDHHmmss"

      - name: Checkout
        uses: actions/checkout@v4

      # =========================
      # Docker meta - SERVER
      # =========================
      - name: Docker meta (server)
        id: docker_meta_server
        uses: crazy-max/ghaction-docker-meta@v5
        with:
          images: |
            kavenzero/${{ github.event.repository.name }}-Server
            ghcr.io/${{ github.repository }}-Server
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=${{ steps.current_date_time.outputs.time }}
            type=raw,value=latest

      # =========================
      # Docker meta - CLIENT
      # =========================
      - name: Docker meta (client)
        id: docker_meta_client
        uses: crazy-max/ghaction-docker-meta@v5
        with:
          images: |
            kavenzero/${{ github.event.repository.name }}-Client
            ghcr.io/${{ github.repository }}-Client
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=${{ steps.current_date_time.outputs.time }}
            type=raw,value=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # =========================
      # Build & Push SERVER
      # =========================
      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./DDNS.Server
          file: ./DDNS.Server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta_server.outputs.tags }}
          labels: ${{ steps.docker_meta_server.outputs.labels }}

      # =========================
      # Build & Push CLIENT
      # =========================
      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./DDNS.Client
          file: ./DDNS.Client/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta_client.outputs.tags }}
          labels: ${{ steps.docker_meta_client.outputs.labels }}
